version: "3.1"
volumes:
  sumers_db:
services:
  db:
    image: mysql:5.7
    command: '--default-authentication-plugin=mysql_native_password'
    secrets:
      - db-password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - sumers_db:/var/lib/mysql        # To mount a docker volume in the container (uncomment lines 2 and 3 above to use this)
      # - /mnt/db:/var/lib/mysql   # To mount a filesystem in the container
  app:
    build: ./app
    restart: always
    secrets:
      - db-password
    links:
      - db
    ports:
      - "5000:5000"               # Change the 2nd number to the port you want visible on the host
secrets:
  db-password:
    file: db/password.txt